[INFO -- 2017-02-25 02:06:28]
Starting flip_value script
version: 2.0
[INFO -- 2017-02-25 02:06:28]
Initialization strings:
[INFO -- 2017-02-25 02:06:28]
(1) target extended-remote | ssh -T mic1 gdbserver --multi -
[INFO -- 2017-02-25 02:06:28]
(2) set sysroot /opt/mpss/3.7/sysroots/k1om-mpss-linux/
[INFO -- 2017-02-25 02:06:28]
(3) set sysroot /opt/mpss/3.7/sysroots/k1om-mpss-linux/
[INFO -- 2017-02-25 02:06:28]
(4) file /micNfs/gdb-fault-injection/injector/bin/lud/lud_check
[INFO -- 2017-02-25 02:06:28]
(5) set remote exec-file /micNfs/gdb-fault-injection/injector/bin/lud/lud_check
[INFO -- 2017-02-25 02:06:28]
(6) set args -s 2048 -n 228 -i /micNfs/gdb-fault-injection/injector/bin/lud/input_2048_th_228 -g /micNfs/gdb-fault-injection/injector/bin/lud/gold_2048_th_228
[INFO -- 2017-02-25 02:06:28]
initSignal:2
[INFO -- 2017-02-25 02:06:28]
endSignal:4
[INFO -- 2017-02-25 02:06:28]
seqSignal:30
[INFO -- 2017-02-25 02:06:28]
faultMode:2
[EXCEPTION -- 2017-02-25 02:06:48]
pythonException: invalid frame
[EXCEPTION -- 2017-02-25 02:06:48]
pythonException: invalid frame
[EXCEPTION -- 2017-02-25 02:06:48]
pythonException: invalid frame
[EXCEPTION -- 2017-02-25 02:06:48]
pythonException: invalid frame
[EXCEPTION -- 2017-02-25 02:06:48]
pythonException: invalid frame
[EXCEPTION -- 2017-02-25 02:06:48]
pythonException: invalid frame
[EXCEPTION -- 2017-02-25 02:06:48]
pythonException: invalid frame
[EXCEPTION -- 2017-02-25 02:06:48]
pythonException: invalid frame
[EXCEPTION -- 2017-02-25 02:06:48]
pythonException: invalid frame
[EXCEPTION -- 2017-02-25 02:06:48]
pythonException: invalid frame
[EXCEPTION -- 2017-02-25 02:06:48]
pythonException: invalid frame
[EXCEPTION -- 2017-02-25 02:06:48]
pythonException: invalid frame
[EXCEPTION -- 2017-02-25 02:06:48]
pythonException: invalid frame
[EXCEPTION -- 2017-02-25 02:06:48]
pythonException: invalid frame
[EXCEPTION -- 2017-02-25 02:06:48]
pythonException: invalid frame
[EXCEPTION -- 2017-02-25 02:06:48]
pythonException: invalid frame
[EXCEPTION -- 2017-02-25 02:06:48]
pythonException: invalid frame
[EXCEPTION -- 2017-02-25 02:06:48]
pythonException: invalid frame
[EXCEPTION -- 2017-02-25 02:06:48]
pythonException: invalid frame
[INFO -- 2017-02-25 02:06:48]
Backtrace BEGIN:
#0  0x0000000000404b59 in L_lud_omp_123__par_loop2_2_5 () at lud_omp.c:139
#1  0x00007ffff790ba1f in ?? ()
#2  0x00007fffffffd9c0 in ?? ()
#3  0x00007ffff4ea0100 in ?? ()
#4  0x0000000000000001 in ?? ()
#5  0x0000000000000003 in ?? ()
#6  0x0000000000000000 in ?? ()

134	
135	            for (i = 0; i < BS; i++) {
136	#pragma omp simd
137	                for (j =0; j < BS; j++){
138	                    temp_top[i*BS + j]  = a[size*(i + offset) + j + j_global ];
139	                    temp_left[i*BS + j] = a[size*(i + i_global) + offset + j];
140	                }
141	            }
142	
143	            for (i = 0; i < BS; i++)

Backtrace END
Memory content before bitflip:0x6d0x000x000x00
Fault Mode: Random bit-flip
base address to flip value: 0x7fffffffd90c
address max offset: 4
Memory content after  bitflip:0xf90xec0x6f0x09
frame name: L_lud_omp_123__par_loop2_2_5
symbol name: chunks_in_inter_row
symbol filename: lud_omp.c
symbol line: 45
value: 158330105
value address: 0x7fffffffd90c
Type: The type is an integer type.
Type sizeof: 4

[INFO -- 2017-02-25 02:06:48]
Fault Injection Successful after 20.5613999367s
[INFO -- 2017-02-25 02:06:52]
event type: exit
[INFO -- 2017-02-25 02:06:52]
exit code: 0
