[INFO -- 2017-03-03 10:47:31]
Starting flip_value script
version: 2.0
[INFO -- 2017-03-03 10:47:31]
Initialization strings:
[INFO -- 2017-03-03 10:47:32]
(1) target extended-remote | ssh -T mic1 gdbserver --multi -
[INFO -- 2017-03-03 10:47:32]
(2) set sysroot /opt/mpss/3.7/sysroots/k1om-mpss-linux/
[INFO -- 2017-03-03 10:47:32]
(3) set sysroot /opt/mpss/3.7/sysroots/k1om-mpss-linux/
[INFO -- 2017-03-03 10:47:32]
(4) file /micNfs/gdb-fault-injection/injector/bin/dgemm/dgemm_check
[INFO -- 2017-03-03 10:47:32]
(5) set remote exec-file /micNfs/gdb-fault-injection/injector/bin/dgemm/dgemm_check
[INFO -- 2017-03-03 10:47:32]
(6) set args 228 2048 16 /micNfs/gdb-fault-injection/injector/bin/dgemm/dgemm_a_8192 /micNfs/gdb-fault-injection/injector/bin/dgemm/dgemm_b_8192 /micNfs/gdb-fault-injection/injector/bin/dgemm/gold_2048_m-order_228_ths_16_blocks 1
[INFO -- 2017-03-03 10:47:32]
initSignal:21
[INFO -- 2017-03-03 10:47:32]
endSignal:28
[INFO -- 2017-03-03 10:47:32]
seqSignal:15
[INFO -- 2017-03-03 10:47:32]
faultMode:2
[EXCEPTION -- 2017-03-03 10:48:05]
pythonException: invalid frame
[EXCEPTION -- 2017-03-03 10:48:05]
pythonException: invalid frame
[EXCEPTION -- 2017-03-03 10:48:05]
pythonException: invalid frame
[EXCEPTION -- 2017-03-03 10:48:05]
pythonException: invalid frame
[EXCEPTION -- 2017-03-03 10:48:05]
pythonException: invalid frame
[EXCEPTION -- 2017-03-03 10:48:05]
pythonException: invalid frame
[EXCEPTION -- 2017-03-03 10:48:05]
pythonException: invalid frame
[EXCEPTION -- 2017-03-03 10:48:05]
pythonException: invalid frame
[EXCEPTION -- 2017-03-03 10:48:05]
pythonException: invalid frame
[EXCEPTION -- 2017-03-03 10:48:05]
pythonException: invalid frame
[EXCEPTION -- 2017-03-03 10:48:05]
pythonException: invalid frame
[EXCEPTION -- 2017-03-03 10:48:05]
pythonException: invalid frame
[EXCEPTION -- 2017-03-03 10:48:05]
pythonException: invalid frame
[EXCEPTION -- 2017-03-03 10:48:05]
pythonException: invalid frame
[EXCEPTION -- 2017-03-03 10:48:05]
pythonException: invalid frame
[EXCEPTION -- 2017-03-03 10:48:05]
pythonException: invalid frame
[INFO -- 2017-03-03 10:48:05]
Backtrace BEGIN:
#0  0x0000000000403355 in L_dgemm_185__par_region0_2_0 () at dgemm.c:212
#1  0x00007ffff790ba1f in ?? ()
#2  0x00007fffffffe550 in ?? ()
#3  0x0000000000000000 in ?? ()

207	
208	                for(ii = 0; ii < order; ii+=block) {
209	
210	                    for (kg=kk,k=0; kg<MIN(kk+block,order); k++,kg++)
211	                        for (ig=ii,i=0; ig<MIN(ii+block,order); i++,ig++)
212	                            AA_arr(i,k) = A_arr(ig,kg);
213	
214	                    for (jg=jj,j=0; jg<MIN(jj+block,order); j++,jg++)
215	                        for (ig=ii,i=0; ig<MIN(ii+block,order); i++,ig++)
216	                            CC_arr(i,j) = 0.0;

Backtrace END
Fliping a bit of the pointer
Memory content before bitflip:0x000x000x000x000x000x000x000x00
Fault Mode: Random bit-flip
base address to flip value: 0x7fffffffdf28
address max offset: 8
Memory content after  bitflip:0x140x900x3d0xa90x810x820x720x6c
frame name: L_dgemm_185__par_region0_2_0
symbol name: B
symbol filename: dgemm.c
symbol line: 181
value: 0x0
value address: 0x7fffffffdf28
Type: The type is a pointer.
Type sizeof: 8

[INFO -- 2017-03-03 10:48:05]
Fault Injection Successful after 33.2465529442s
[INFO -- 2017-03-03 10:48:20]
event type: exit
[INFO -- 2017-03-03 10:48:20]
exit code: 0
