[INFO -- 2017-03-08 09:02:00]
Starting flip_value script
version: 2.0
[INFO -- 2017-03-08 09:02:00]
Initialization strings:
[INFO -- 2017-03-08 09:02:00]
(1) target extended-remote | ssh -T mic1 gdbserver --multi -
[INFO -- 2017-03-08 09:02:00]
(2) set sysroot /opt/mpss/3.7/sysroots/k1om-mpss-linux/
[INFO -- 2017-03-08 09:02:00]
(3) set sysroot /opt/mpss/3.7/sysroots/k1om-mpss-linux/
[INFO -- 2017-03-08 09:02:00]
(4) file /micNfs/gdb-fault-injection/injector/bin/dgemm/dgemm_check
[INFO -- 2017-03-08 09:02:00]
(5) set remote exec-file /micNfs/gdb-fault-injection/injector/bin/dgemm/dgemm_check
[INFO -- 2017-03-08 09:02:00]
(6) set args 228 2048 16 /micNfs/gdb-fault-injection/injector/bin/dgemm/dgemm_a_8192 /micNfs/gdb-fault-injection/injector/bin/dgemm/dgemm_b_8192 /micNfs/gdb-fault-injection/injector/bin/dgemm/gold_2048_m-order_228_ths_16_blocks 1
[INFO -- 2017-03-08 09:02:00]
initSignal:28
[INFO -- 2017-03-08 09:02:00]
endSignal:28
[INFO -- 2017-03-08 09:02:00]
seqSignal:15
[INFO -- 2017-03-08 09:02:00]
faultMode:0
[EXCEPTION -- 2017-03-08 09:02:33]
pythonException: invalid frame
[EXCEPTION -- 2017-03-08 09:02:33]
pythonException: invalid frame
[EXCEPTION -- 2017-03-08 09:02:33]
pythonException: invalid frame
[EXCEPTION -- 2017-03-08 09:02:33]
pythonException: invalid frame
[EXCEPTION -- 2017-03-08 09:02:33]
pythonException: invalid frame
[EXCEPTION -- 2017-03-08 09:02:33]
pythonException: invalid frame
[EXCEPTION -- 2017-03-08 09:02:33]
pythonException: invalid frame
[EXCEPTION -- 2017-03-08 09:02:33]
pythonException: invalid frame
[EXCEPTION -- 2017-03-08 09:02:33]
pythonException: invalid frame
[EXCEPTION -- 2017-03-08 09:02:33]
pythonException: invalid frame
[EXCEPTION -- 2017-03-08 09:02:33]
pythonException: invalid frame
[EXCEPTION -- 2017-03-08 09:02:33]
pythonException: invalid frame
[EXCEPTION -- 2017-03-08 09:02:33]
pythonException: invalid frame
[EXCEPTION -- 2017-03-08 09:02:33]
pythonException: invalid frame
[EXCEPTION -- 2017-03-08 09:02:33]
pythonException: invalid frame
[EXCEPTION -- 2017-03-08 09:02:33]
pythonException: invalid frame
[INFO -- 2017-03-08 09:02:33]
Backtrace BEGIN:
#0  0x0000000000403355 in L_dgemm_185__par_region0_2_0 () at dgemm.c:212
#1  0x00007ffff790ba1f in ?? ()
#2  0x00007fffffffe550 in ?? ()
#3  0x0000000000000000 in ?? ()

207	
208	                for(ii = 0; ii < order; ii+=block) {
209	
210	                    for (kg=kk,k=0; kg<MIN(kk+block,order); k++,kg++)
211	                        for (ig=ii,i=0; ig<MIN(ii+block,order); i++,ig++)
212	                            AA_arr(i,k) = A_arr(ig,kg);
213	
214	                    for (jg=jj,j=0; jg<MIN(jj+block,order); j++,jg++)
215	                        for (ig=ii,i=0; ig<MIN(ii+block,order); i++,ig++)
216	                            CC_arr(i,j) = 0.0;

Backtrace END
Memory content before bitflip:0x000x000x000x00
Fault Mode: Single bit-flip
base address to flip value: 0x7fffffffde90
address max offset: 4
Memory content after  bitflip:0x040x000x000x00
frame name: L_dgemm_185__par_region0_2_0
symbol name: kg
symbol filename: dgemm.c
symbol line: 183
value: 4
value address: 0x7fffffffde90
Type: The type is an integer type.
Type sizeof: 4

[INFO -- 2017-03-08 09:02:33]
Fault Injection Successful after 33.3077790737s
