[INFO -- 2017-02-25 14:33:46]
Starting flip_value script
version: 2.0
[INFO -- 2017-02-25 14:33:46]
Initialization strings:
[INFO -- 2017-02-25 14:33:46]
(1) target extended-remote | ssh -T mic1 gdbserver --multi -
[INFO -- 2017-02-25 14:33:46]
(2) set sysroot /opt/mpss/3.7/sysroots/k1om-mpss-linux/
[INFO -- 2017-02-25 14:33:46]
(3) set sysroot /opt/mpss/3.7/sysroots/k1om-mpss-linux/
[INFO -- 2017-02-25 14:33:46]
(4) file /micNfs/gdb-fault-injection/injector/bin/lud/lud_check
[INFO -- 2017-02-25 14:33:46]
(5) set remote exec-file /micNfs/gdb-fault-injection/injector/bin/lud/lud_check
[INFO -- 2017-02-25 14:33:46]
(6) set args -s 2048 -n 228 -i /micNfs/gdb-fault-injection/injector/bin/lud/input_2048_th_228 -g /micNfs/gdb-fault-injection/injector/bin/lud/gold_2048_th_228
[INFO -- 2017-02-25 14:33:46]
initSignal:4
[INFO -- 2017-02-25 14:33:46]
endSignal:8
[INFO -- 2017-02-25 14:33:46]
seqSignal:30
[INFO -- 2017-02-25 14:33:46]
faultMode:3
[EXCEPTION -- 2017-02-25 14:34:05]
pythonException: invalid frame
[EXCEPTION -- 2017-02-25 14:34:05]
pythonException: invalid frame
[EXCEPTION -- 2017-02-25 14:34:05]
pythonException: invalid frame
[EXCEPTION -- 2017-02-25 14:34:05]
pythonException: invalid frame
[EXCEPTION -- 2017-02-25 14:34:05]
pythonException: invalid frame
[EXCEPTION -- 2017-02-25 14:34:05]
pythonException: invalid frame
[EXCEPTION -- 2017-02-25 14:34:05]
pythonException: invalid frame
[EXCEPTION -- 2017-02-25 14:34:05]
pythonException: invalid frame
[EXCEPTION -- 2017-02-25 14:34:05]
pythonException: invalid frame
[EXCEPTION -- 2017-02-25 14:34:05]
pythonException: invalid frame
[EXCEPTION -- 2017-02-25 14:34:05]
pythonException: invalid frame
[EXCEPTION -- 2017-02-25 14:34:05]
pythonException: invalid frame
[EXCEPTION -- 2017-02-25 14:34:05]
pythonException: invalid frame
[EXCEPTION -- 2017-02-25 14:34:05]
pythonException: invalid frame
[EXCEPTION -- 2017-02-25 14:34:05]
pythonException: invalid frame
[EXCEPTION -- 2017-02-25 14:34:05]
pythonException: invalid frame
[EXCEPTION -- 2017-02-25 14:34:05]
pythonException: invalid frame
[EXCEPTION -- 2017-02-25 14:34:05]
pythonException: invalid frame
[EXCEPTION -- 2017-02-25 14:34:05]
pythonException: invalid frame
[EXCEPTION -- 2017-02-25 14:34:05]
pythonException: invalid frame
[EXCEPTION -- 2017-02-25 14:34:05]
pythonException: invalid frame
[INFO -- 2017-02-25 14:34:05]
Backtrace BEGIN:
#0  0x0000000000404d1f in L_lud_omp_123__par_loop2_2_5 () at lud_omp.c:147
#1  0x00007ffff790ba1f in ?? ()
#2  0x00007fffffffd9c0 in ?? ()
#3  0x00007ffff4ea0100 in ?? ()
#4  0x0000000000000001 in ?? ()
#5  0x0000000000000003 in ?? ()
#6  0x0000000000000000 in ?? ()

142	
143	            for (i = 0; i < BS; i++)
144	            {
145	                for (k=0; k < BS; k++) {
146	#pragma omp simd 
147	                    for (j = 0; j < BS; j++) {
148	                        sum[j] += temp_left[BS*i + k] * temp_top[BS*k + j];
149	                    }
150	                }
151	#pragma omp simd 

Backtrace END
Fliping array at pos: 15
Memory content before bitflip:0x5e0xd30x6d0x3e
Fault Mode: Zero bit-flip
base address to flip value: 0x7fffffffc87c
address max offset: 4
Memory content after  bitflip:0x000x000x000x00
frame name: L_lud_omp_123__par_loop2_2_5
symbol name: sum
symbol filename: lud_omp.c
symbol line: 130
value: {0.25285694, 0.252605021, 0.252351075, 0.252099007, 0.234818712, 0.234585419, 0.234349847, 0.234115794, 0.23388207, 0.233647525, 0.23341544, 0.233180493, 0.232948437, 0.232715055, 0.232482627, 0}
value address: 0x7fffffffc840
Type: The type is an array.
Type sizeof: 64
Field name: None
Field Type: A range type, that is, an integer type with bounds.
Field Type sizeof: 1
Field Type range: (0L, 15L)

[INFO -- 2017-02-25 14:34:05]
Fault Injection Successful after 19.9217119217s
[INFO -- 2017-02-25 14:34:13]
event type: exit
[INFO -- 2017-02-25 14:34:13]
exit code: 1
