[INFO -- 2017-02-25 04:47:22]
Starting flip_value script
version: 2.0
[INFO -- 2017-02-25 04:47:22]
Initialization strings:
[INFO -- 2017-02-25 04:47:22]
(1) target extended-remote | ssh -T mic1 gdbserver --multi -
[INFO -- 2017-02-25 04:47:22]
(2) set sysroot /opt/mpss/3.7/sysroots/k1om-mpss-linux/
[INFO -- 2017-02-25 04:47:22]
(3) set sysroot /opt/mpss/3.7/sysroots/k1om-mpss-linux/
[INFO -- 2017-02-25 04:47:22]
(4) file /micNfs/gdb-fault-injection/injector/bin/lud/lud_check
[INFO -- 2017-02-25 04:47:22]
(5) set remote exec-file /micNfs/gdb-fault-injection/injector/bin/lud/lud_check
[INFO -- 2017-02-25 04:47:22]
(6) set args -s 2048 -n 228 -i /micNfs/gdb-fault-injection/injector/bin/lud/input_2048_th_228 -g /micNfs/gdb-fault-injection/injector/bin/lud/gold_2048_th_228
[INFO -- 2017-02-25 04:47:22]
initSignal:4
[INFO -- 2017-02-25 04:47:22]
endSignal:8
[INFO -- 2017-02-25 04:47:22]
seqSignal:30
[INFO -- 2017-02-25 04:47:22]
faultMode:2
[EXCEPTION -- 2017-02-25 04:47:32]
pythonException: invalid frame
[EXCEPTION -- 2017-02-25 04:47:32]
pythonException: invalid frame
[EXCEPTION -- 2017-02-25 04:47:32]
pythonException: invalid frame
[EXCEPTION -- 2017-02-25 04:47:32]
pythonException: invalid frame
[EXCEPTION -- 2017-02-25 04:47:32]
pythonException: invalid frame
[EXCEPTION -- 2017-02-25 04:47:32]
pythonException: invalid frame
[EXCEPTION -- 2017-02-25 04:47:32]
pythonException: invalid frame
[EXCEPTION -- 2017-02-25 04:47:32]
pythonException: invalid frame
[EXCEPTION -- 2017-02-25 04:47:32]
pythonException: invalid frame
[EXCEPTION -- 2017-02-25 04:47:32]
pythonException: invalid frame
[EXCEPTION -- 2017-02-25 04:47:32]
pythonException: invalid frame
[EXCEPTION -- 2017-02-25 04:47:32]
pythonException: invalid frame
[EXCEPTION -- 2017-02-25 04:47:32]
pythonException: invalid frame
[EXCEPTION -- 2017-02-25 04:47:32]
pythonException: invalid frame
[EXCEPTION -- 2017-02-25 04:47:32]
pythonException: invalid frame
[EXCEPTION -- 2017-02-25 04:47:32]
pythonException: invalid frame
[EXCEPTION -- 2017-02-25 04:47:32]
pythonException: invalid frame
[EXCEPTION -- 2017-02-25 04:47:32]
pythonException: invalid frame
[EXCEPTION -- 2017-02-25 04:47:32]
pythonException: invalid frame
[EXCEPTION -- 2017-02-25 04:47:32]
pythonException: invalid frame
[EXCEPTION -- 2017-02-25 04:47:32]
pythonException: invalid frame
[EXCEPTION -- 2017-02-25 04:47:32]
pythonException: invalid frame
[EXCEPTION -- 2017-02-25 04:47:32]
pythonException: invalid frame
[EXCEPTION -- 2017-02-25 04:47:32]
pythonException: invalid frame
[EXCEPTION -- 2017-02-25 04:47:32]
pythonException: invalid frame
[EXCEPTION -- 2017-02-25 04:47:32]
pythonException: invalid frame
[EXCEPTION -- 2017-02-25 04:47:32]
pythonException: invalid frame
[INFO -- 2017-02-25 04:47:32]
Backtrace BEGIN:
#0  0x0000000000404d9d in L_lud_omp_123__par_loop2_2_5 () at lud_omp.c:153
#1  0x00007ffff790ba1f in ?? ()
#2  0x00007fffffffd9c0 in ?? ()
#3  0x00007ffff4ea0100 in ?? ()
#4  0x0000000000000001 in ?? ()
#5  0x0000000000000003 in ?? ()
#6  0x0000000000000000 in ?? ()

148	                        sum[j] += temp_left[BS*i + k] * temp_top[BS*k + j];
149	                    }
150	                }
151	#pragma omp simd 
152	                for (j = 0; j < BS; j++) {
153	                    BB((i+i_global),(j+j_global)) -= sum[j];
154	                    sum[j] = 0.f;
155	                }
156	            }
157	        }

Backtrace END
Memory content before bitflip:0x600x070x000x00
Fault Mode: Random bit-flip
base address to flip value: 0x7fffffffc698
address max offset: 4
Memory content after  bitflip:0x550x700x9c0x32
frame name: L_lud_omp_123__par_loop2_2_5
symbol name: i_global
symbol filename: lud_omp.c
symbol line: 127
value: 849113173
value address: 0x7fffffffc698
Type: The type is an integer type.
Type sizeof: 4

[INFO -- 2017-02-25 04:47:32]
Fault Injection Successful after 10.9043459892s
[INFO -- 2017-02-25 04:47:33]
event type: exit
[EXCEPTION -- 2017-02-25 04:47:33]
exit code: no exit code available
