[INFO -- 2017-02-26 21:31:09]
Starting flip_value script
version: 2.0
[INFO -- 2017-02-26 21:31:09]
Initialization strings:
[INFO -- 2017-02-26 21:31:09]
(1) target extended-remote | ssh -T mic1 gdbserver --multi -
[INFO -- 2017-02-26 21:31:09]
(2) set sysroot /opt/mpss/3.7/sysroots/k1om-mpss-linux/
[INFO -- 2017-02-26 21:31:09]
(3) set sysroot /opt/mpss/3.7/sysroots/k1om-mpss-linux/
[INFO -- 2017-02-26 21:31:09]
(4) file /micNfs/gdb-fault-injection/injector/bin/lud/lud_check
[INFO -- 2017-02-26 21:31:09]
(5) set remote exec-file /micNfs/gdb-fault-injection/injector/bin/lud/lud_check
[INFO -- 2017-02-26 21:31:09]
(6) set args -s 2048 -n 228 -i /micNfs/gdb-fault-injection/injector/bin/lud/input_2048_th_228 -g /micNfs/gdb-fault-injection/injector/bin/lud/gold_2048_th_228
[INFO -- 2017-02-26 21:31:09]
initSignal:4
[INFO -- 2017-02-26 21:31:09]
endSignal:8
[INFO -- 2017-02-26 21:31:09]
seqSignal:30
[INFO -- 2017-02-26 21:31:09]
faultMode:2
[EXCEPTION -- 2017-02-26 21:31:20]
pythonException: invalid frame
[EXCEPTION -- 2017-02-26 21:31:20]
pythonException: invalid frame
[EXCEPTION -- 2017-02-26 21:31:20]
pythonException: invalid frame
[EXCEPTION -- 2017-02-26 21:31:20]
pythonException: invalid frame
[EXCEPTION -- 2017-02-26 21:31:20]
pythonException: invalid frame
[EXCEPTION -- 2017-02-26 21:31:20]
pythonException: invalid frame
[EXCEPTION -- 2017-02-26 21:31:20]
pythonException: invalid frame
[EXCEPTION -- 2017-02-26 21:31:20]
pythonException: invalid frame
[EXCEPTION -- 2017-02-26 21:31:20]
pythonException: invalid frame
[EXCEPTION -- 2017-02-26 21:31:20]
pythonException: invalid frame
[EXCEPTION -- 2017-02-26 21:31:20]
pythonException: invalid frame
[EXCEPTION -- 2017-02-26 21:31:20]
pythonException: invalid frame
[EXCEPTION -- 2017-02-26 21:31:20]
pythonException: invalid frame
[EXCEPTION -- 2017-02-26 21:31:20]
pythonException: invalid frame
[EXCEPTION -- 2017-02-26 21:31:20]
pythonException: invalid frame
[EXCEPTION -- 2017-02-26 21:31:20]
pythonException: invalid frame
[EXCEPTION -- 2017-02-26 21:31:20]
pythonException: invalid frame
[EXCEPTION -- 2017-02-26 21:31:20]
pythonException: invalid frame
[EXCEPTION -- 2017-02-26 21:31:20]
pythonException: invalid frame
[EXCEPTION -- 2017-02-26 21:31:20]
pythonException: invalid frame
[INFO -- 2017-02-26 21:31:20]
Backtrace BEGIN:
#0  0x0000000000404c7c in L_lud_omp_123__par_loop2_2_5 () at lud_omp.c:148
#1  0x00007ffff790ba1f in ?? ()
#2  0x00007fffffffd9c0 in ?? ()
#3  0x00007ffff4ea0100 in ?? ()
#4  0x0000000000000001 in ?? ()
#5  0x0000000000000003 in ?? ()
#6  0x0000000000000000 in ?? ()

143	            for (i = 0; i < BS; i++)
144	            {
145	                for (k=0; k < BS; k++) {
146	#pragma omp simd 
147	                    for (j = 0; j < BS; j++) {
148	                        sum[j] += temp_left[BS*i + k] * temp_top[BS*k + j];
149	                    }
150	                }
151	#pragma omp simd 
152	                for (j = 0; j < BS; j++) {

Backtrace END
Fliping array at pos: 4
Memory content before bitflip:0x440xc80xea0x3c
Fault Mode: Random bit-flip
base address to flip value: 0x7fffffffc850
address max offset: 4
Memory content after  bitflip:0xdf0x5e0x0d0x61
frame name: L_lud_omp_123__par_loop2_2_5
symbol name: sum
symbol filename: lud_omp.c
symbol line: 130
value: {0.0287757851, 0.0287461877, 0.0287171882, 0.0286889747, 1.62989194e+20, 0.0286317319, 0.0286032576, 0.0285751279, 0.0285463277, 0.0285182297, 0.028489273, 0.0284598507, 0.0284318421, 0.0236458387, 0.0236214958, 0.0235988237}
value address: 0x7fffffffc840
Type: The type is an array.
Type sizeof: 64
Field name: None
Field Type: A range type, that is, an integer type with bounds.
Field Type sizeof: 1
Field Type range: (0L, 15L)

[INFO -- 2017-02-26 21:31:20]
Fault Injection Successful after 11.6679830551s
[INFO -- 2017-02-26 21:31:30]
event type: exit
[INFO -- 2017-02-26 21:31:30]
exit code: 1
