[INFO -- 2017-02-26 23:50:51]
Starting flip_value script
version: 2.0
[INFO -- 2017-02-26 23:50:51]
Initialization strings:
[INFO -- 2017-02-26 23:50:51]
(1) target extended-remote | ssh -T mic1 gdbserver --multi -
[INFO -- 2017-02-26 23:50:51]
(2) set sysroot /opt/mpss/3.7/sysroots/k1om-mpss-linux/
[INFO -- 2017-02-26 23:50:51]
(3) set sysroot /opt/mpss/3.7/sysroots/k1om-mpss-linux/
[INFO -- 2017-02-26 23:50:51]
(4) file /micNfs/gdb-fault-injection/injector/bin/lud/lud_check
[INFO -- 2017-02-26 23:50:51]
(5) set remote exec-file /micNfs/gdb-fault-injection/injector/bin/lud/lud_check
[INFO -- 2017-02-26 23:50:51]
(6) set args -s 2048 -n 228 -i /micNfs/gdb-fault-injection/injector/bin/lud/input_2048_th_228 -g /micNfs/gdb-fault-injection/injector/bin/lud/gold_2048_th_228
[INFO -- 2017-02-26 23:50:51]
initSignal:2
[INFO -- 2017-02-26 23:50:51]
endSignal:4
[INFO -- 2017-02-26 23:50:51]
seqSignal:30
[INFO -- 2017-02-26 23:50:51]
faultMode:2
[EXCEPTION -- 2017-02-26 23:51:03]
pythonException: invalid frame
[EXCEPTION -- 2017-02-26 23:51:03]
pythonException: invalid frame
[EXCEPTION -- 2017-02-26 23:51:03]
pythonException: invalid frame
[EXCEPTION -- 2017-02-26 23:51:03]
pythonException: invalid frame
[EXCEPTION -- 2017-02-26 23:51:03]
pythonException: invalid frame
[EXCEPTION -- 2017-02-26 23:51:03]
pythonException: invalid frame
[EXCEPTION -- 2017-02-26 23:51:03]
pythonException: invalid frame
[EXCEPTION -- 2017-02-26 23:51:03]
pythonException: invalid frame
[EXCEPTION -- 2017-02-26 23:51:03]
pythonException: invalid frame
[EXCEPTION -- 2017-02-26 23:51:03]
pythonException: invalid frame
[EXCEPTION -- 2017-02-26 23:51:03]
pythonException: invalid frame
[EXCEPTION -- 2017-02-26 23:51:03]
pythonException: invalid frame
[EXCEPTION -- 2017-02-26 23:51:03]
pythonException: invalid frame
[EXCEPTION -- 2017-02-26 23:51:03]
pythonException: invalid frame
[EXCEPTION -- 2017-02-26 23:51:03]
pythonException: invalid frame
[EXCEPTION -- 2017-02-26 23:51:03]
pythonException: invalid frame
[EXCEPTION -- 2017-02-26 23:51:03]
pythonException: invalid frame
[EXCEPTION -- 2017-02-26 23:51:03]
pythonException: invalid frame
[EXCEPTION -- 2017-02-26 23:51:03]
pythonException: invalid frame
[INFO -- 2017-02-26 23:51:03]
Backtrace BEGIN:
#0  0x0000000000404ace in L_lud_omp_123__par_loop2_2_5 () at lud_omp.c:138
#1  0x00007ffff790ba1f in ?? ()
#2  0x00007fffffffd9c0 in ?? ()
#3  0x00007ffff4ea0100 in ?? ()
#4  0x0000000000000001 in ?? ()
#5  0x0000000000000003 in ?? ()
#6  0x0000000000000000 in ?? ()

133	            j_global = offset + BS * (1 + chunk_idx%chunks_in_inter_row);
134	
135	            for (i = 0; i < BS; i++) {
136	#pragma omp simd
137	                for (j =0; j < BS; j++){
138	                    temp_top[i*BS + j]  = a[size*(i + offset) + j + j_global ];
139	                    temp_left[i*BS + j] = a[size*(i + i_global) + offset + j];
140	                }
141	            }
142	

Backtrace END
Memory content before bitflip:0x1c0x000x000x00
Fault Mode: Random bit-flip
base address to flip value: 0x7fffffffc688
address max offset: 4
Memory content after  bitflip:0x220x290x310x23
frame name: L_lud_omp_123__par_loop2_2_5
symbol name: size_inter
symbol filename: lud_omp.c
symbol line: 45
value: 590424354
value address: 0x7fffffffc688
Type: The type is an integer type.
Type sizeof: 4

[INFO -- 2017-02-26 23:51:03]
Fault Injection Successful after 12.9967141151s
[INFO -- 2017-02-26 23:51:11]
event type: exit
[INFO -- 2017-02-26 23:51:11]
exit code: 0
