[INFO -- 2017-02-25 23:51:12]
Starting flip_value script
version: 2.0
[INFO -- 2017-02-25 23:51:12]
Initialization strings:
[INFO -- 2017-02-25 23:51:12]
(1) target extended-remote | ssh -T mic1 gdbserver --multi -
[INFO -- 2017-02-25 23:51:12]
(2) set sysroot /opt/mpss/3.7/sysroots/k1om-mpss-linux/
[INFO -- 2017-02-25 23:51:12]
(3) set sysroot /opt/mpss/3.7/sysroots/k1om-mpss-linux/
[INFO -- 2017-02-25 23:51:12]
(4) file /micNfs/gdb-fault-injection/injector/bin/lud/lud_check
[INFO -- 2017-02-25 23:51:12]
(5) set remote exec-file /micNfs/gdb-fault-injection/injector/bin/lud/lud_check
[INFO -- 2017-02-25 23:51:12]
(6) set args -s 2048 -n 228 -i /micNfs/gdb-fault-injection/injector/bin/lud/input_2048_th_228 -g /micNfs/gdb-fault-injection/injector/bin/lud/gold_2048_th_228
[INFO -- 2017-02-25 23:51:12]
initSignal:4
[INFO -- 2017-02-25 23:51:12]
endSignal:8
[INFO -- 2017-02-25 23:51:12]
seqSignal:30
[INFO -- 2017-02-25 23:51:12]
faultMode:2
[EXCEPTION -- 2017-02-25 23:51:23]
pythonException: invalid frame
[EXCEPTION -- 2017-02-25 23:51:23]
pythonException: invalid frame
[EXCEPTION -- 2017-02-25 23:51:23]
pythonException: invalid frame
[EXCEPTION -- 2017-02-25 23:51:23]
pythonException: invalid frame
[EXCEPTION -- 2017-02-25 23:51:23]
pythonException: invalid frame
[EXCEPTION -- 2017-02-25 23:51:23]
pythonException: invalid frame
[EXCEPTION -- 2017-02-25 23:51:23]
pythonException: invalid frame
[EXCEPTION -- 2017-02-25 23:51:23]
pythonException: invalid frame
[EXCEPTION -- 2017-02-25 23:51:23]
pythonException: invalid frame
[EXCEPTION -- 2017-02-25 23:51:23]
pythonException: invalid frame
[EXCEPTION -- 2017-02-25 23:51:23]
pythonException: invalid frame
[EXCEPTION -- 2017-02-25 23:51:23]
pythonException: invalid frame
[EXCEPTION -- 2017-02-25 23:51:23]
pythonException: invalid frame
[EXCEPTION -- 2017-02-25 23:51:23]
pythonException: invalid frame
[EXCEPTION -- 2017-02-25 23:51:23]
pythonException: invalid frame
[EXCEPTION -- 2017-02-25 23:51:23]
pythonException: invalid frame
[EXCEPTION -- 2017-02-25 23:51:23]
pythonException: invalid frame
[EXCEPTION -- 2017-02-25 23:51:23]
pythonException: invalid frame
[EXCEPTION -- 2017-02-25 23:51:23]
pythonException: invalid frame
[EXCEPTION -- 2017-02-25 23:51:23]
pythonException: invalid frame
[EXCEPTION -- 2017-02-25 23:51:23]
pythonException: invalid frame
[EXCEPTION -- 2017-02-25 23:51:23]
pythonException: invalid frame
[EXCEPTION -- 2017-02-25 23:51:23]
pythonException: invalid frame
[EXCEPTION -- 2017-02-25 23:51:23]
pythonException: invalid frame
[EXCEPTION -- 2017-02-25 23:51:23]
pythonException: invalid frame
[EXCEPTION -- 2017-02-25 23:51:23]
pythonException: invalid frame
[INFO -- 2017-02-25 23:51:23]
Backtrace BEGIN:
#0  0x0000000000404c74 in L_lud_omp_123__par_loop2_2_5 () at lud_omp.c:148
#1  0x00007ffff790ba1f in ?? ()
#2  0x00007fffffffd9c0 in ?? ()
#3  0x00007ffff4ea0100 in ?? ()
#4  0x0000000000000001 in ?? ()
#5  0x0000000000000003 in ?? ()
#6  0x0000000000000000 in ?? ()

143	            for (i = 0; i < BS; i++)
144	            {
145	                for (k=0; k < BS; k++) {
146	#pragma omp simd 
147	                    for (j = 0; j < BS; j++) {
148	                        sum[j] += temp_left[BS*i + k] * temp_top[BS*k + j];
149	                    }
150	                }
151	#pragma omp simd 
152	                for (j = 0; j < BS; j++) {

Backtrace END
Memory content before bitflip:0x1c0x000x000x00
Fault Mode: Random bit-flip
base address to flip value: 0x7fffffffc688
address max offset: 4
Memory content after  bitflip:0xdc0x210x130x94
frame name: L_lud_omp_123__par_loop2_2_5
symbol name: size_inter
symbol filename: lud_omp.c
symbol line: 45
value: -1810685476
value address: 0x7fffffffc688
Type: The type is an integer type.
Type sizeof: 4

[INFO -- 2017-02-25 23:51:23]
Fault Injection Successful after 11.928581953s
[INFO -- 2017-02-25 23:51:31]
event type: exit
[INFO -- 2017-02-25 23:51:31]
exit code: 0
