[INFO -- 2017-03-07 10:22:29]
Starting flip_value script
version: 2.0
[INFO -- 2017-03-07 10:22:29]
Initialization strings:
[INFO -- 2017-03-07 10:22:29]
(1) target extended-remote | ssh -T mic0 gdbserver --multi -
[INFO -- 2017-03-07 10:22:29]
(2) set sysroot /opt/mpss/3.7/sysroots/k1om-mpss-linux/
[INFO -- 2017-03-07 10:22:29]
(3) set sysroot /opt/mpss/3.7/sysroots/k1om-mpss-linux/
[INFO -- 2017-03-07 10:22:29]
(4) file /micNfs/gdb-fault-injection/injector/bin/lud/lud_check
[INFO -- 2017-03-07 10:22:29]
(5) set remote exec-file /micNfs/gdb-fault-injection/injector/bin/lud/lud_check
[INFO -- 2017-03-07 10:22:29]
(6) set args -s 2048 -n 228 -i /micNfs/gdb-fault-injection/injector/bin/lud/input_2048_th_228 -g /micNfs/gdb-fault-injection/injector/bin/lud/gold_2048_th_228
[INFO -- 2017-03-07 10:22:29]
initSignal:4
[INFO -- 2017-03-07 10:22:29]
endSignal:6
[INFO -- 2017-03-07 10:22:29]
seqSignal:30
[INFO -- 2017-03-07 10:22:29]
faultMode:2
[EXCEPTION -- 2017-03-07 10:22:40]
pythonException: invalid frame
[EXCEPTION -- 2017-03-07 10:22:40]
pythonException: invalid frame
[EXCEPTION -- 2017-03-07 10:22:40]
pythonException: invalid frame
[EXCEPTION -- 2017-03-07 10:22:40]
pythonException: invalid frame
[EXCEPTION -- 2017-03-07 10:22:40]
pythonException: invalid frame
[EXCEPTION -- 2017-03-07 10:22:40]
pythonException: invalid frame
[EXCEPTION -- 2017-03-07 10:22:40]
pythonException: invalid frame
[EXCEPTION -- 2017-03-07 10:22:40]
pythonException: invalid frame
[EXCEPTION -- 2017-03-07 10:22:40]
pythonException: invalid frame
[EXCEPTION -- 2017-03-07 10:22:40]
pythonException: invalid frame
[EXCEPTION -- 2017-03-07 10:22:40]
pythonException: invalid frame
[EXCEPTION -- 2017-03-07 10:22:40]
pythonException: invalid frame
[EXCEPTION -- 2017-03-07 10:22:40]
pythonException: invalid frame
[EXCEPTION -- 2017-03-07 10:22:40]
pythonException: invalid frame
[EXCEPTION -- 2017-03-07 10:22:40]
pythonException: invalid frame
[EXCEPTION -- 2017-03-07 10:22:40]
pythonException: invalid frame
[EXCEPTION -- 2017-03-07 10:22:40]
pythonException: invalid frame
[EXCEPTION -- 2017-03-07 10:22:40]
pythonException: invalid frame
[EXCEPTION -- 2017-03-07 10:22:40]
pythonException: invalid frame
[INFO -- 2017-03-07 10:22:40]
Backtrace BEGIN:
#0  0x0000000000404cd8 in L_lud_omp_123__par_loop2_2_5 () at lud_omp.c:148
#1  0x00007ffff790ba1f in ?? ()
#2  0x00007fffffffd9c0 in ?? ()
#3  0x00007ffff4ea0100 in ?? ()
#4  0x0000000000000001 in ?? ()
#5  0x0000000000000003 in ?? ()
#6  0x0000000000000000 in ?? ()

143	            for (i = 0; i < BS; i++)
144	            {
145	                for (k=0; k < BS; k++) {
146	#pragma omp simd 
147	                    for (j = 0; j < BS; j++) {
148	                        sum[j] += temp_left[BS*i + k] * temp_top[BS*k + j];
149	                    }
150	                }
151	#pragma omp simd 
152	                for (j = 0; j < BS; j++) {

Backtrace END
Fliping array at pos: 8
Memory content before bitflip:0xd00xf80x910x3e
Fault Mode: Random bit-flip
base address to flip value: 0x7fffffffc860
address max offset: 4
Memory content after  bitflip:0x750x1f0x480xf9
frame name: L_lud_omp_123__par_loop2_2_5
symbol name: sum
symbol filename: lud_omp.c
symbol line: 130
value: {0.306851804, 0.306553066, 0.28681317, 0.286524832, 0.28624168, 0.285953671, 0.285669625, 0.285385847, -6.49435873e+34, 0.284815431, 0.284530669, 0.284242094, 0.283960193, 0.283676952, 0.283398449, 0.283113658}
value address: 0x7fffffffc840
Type: The type is an array.
Type sizeof: 64
Field name: None
Field Type: A range type, that is, an integer type with bounds.
Field Type sizeof: 1
Field Type range: (0L, 15L)

[INFO -- 2017-03-07 10:22:40]
Fault Injection Successful after 11.9599161148s
[INFO -- 2017-03-07 10:22:49]
event type: exit
[INFO -- 2017-03-07 10:22:49]
exit code: 1
